mqtt:
  enabled: false

model:
  path: /config/models/best-255_saved_model/best-255_float32.tflite
  width: 640
  height: 640
  input_tensor: "nhwc"
  input_pixel_format: "rgb"

cameras:
  cam-1:
    enabled: true
    ffmpeg:
#      global_args: -hide_banner
#      haccel_args: preset-nvidia-h264
#      protection_mode: off
      inputs:
      - path: rtsp://192.168.1.22:554/stream=0
        roles:
        - detect

    zones:
      player_1:
        coordinates: 175,1139,210,0,2001,0,2001,1140
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    required_zones:
      - player_1
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  timestamp: true
  required_zones:
    - player_1

